import { DEFAULT_STATIC_URL_SEARCH_PARAMS } from '../config/constants';
import { expect, test } from '../fixtures';

test.describe('Native Histogram', () => {
  test.beforeEach(async ({ selectMetricView }) => {
    await selectMetricView.goto(DEFAULT_STATIC_URL_SEARCH_PARAMS);
  });

  test('From select metrics', async ({ selectMetricView }) => {
    const NATIVE_HISTOGRAM_LABEL = `grafana_database_all_migrations_duration_seconds`;

    await selectMetricView.quickSearch.enterText(NATIVE_HISTOGRAM_LABEL);
    await selectMetricView.assertPanel(NATIVE_HISTOGRAM_LABEL);

    // we take a screenshot because the badge is displayed via a CSS pseudo element and text assertions do not work
    // we take a screenshot of the whole panel and not only the header because the selector generated by Grafana Dev 12 is different from Grafana enterprise 11
    await expect(selectMetricView.getPanelByTitle(NATIVE_HISTOGRAM_LABEL)).toHaveScreenshot(
      'native-histogram-panel.png'
    );
  });
});
