import { test } from '../fixtures';

test.describe('Native histograms', () => {
  test.beforeEach(async ({ metricsReducerView }) => {
    await metricsReducerView.goto();
  });

  test('Native histogram panels display an info badge', async ({ metricsReducerView, expectToHaveScreenshot }) => {
    const METRIC_NAME = `grafana_database_all_migrations_duration_seconds`;

    await metricsReducerView.quickSearch.enterText(METRIC_NAME);
    await metricsReducerView.assertPanel(METRIC_NAME);

    // we take a screenshot because the badge is displayed via a CSS pseudo element and text assertions do not work
    // we take a screenshot of the whole panel and not only the header because the selector generated by Grafana Dev 12 is different from Grafana enterprise 11
    await expectToHaveScreenshot(metricsReducerView.getPanelByTitle(METRIC_NAME), 'native-histogram-panel.png');
  });
});
