import { expect, test } from '../fixtures';

test.describe('Native histograms', () => {
  test('Native histogram panels display an info badge', async ({ metricsReducerView }) => {
    const METRIC_NAME = `grafana_database_all_migrations_duration_seconds`;
    await metricsReducerView.goto(new URLSearchParams([['search_txt', METRIC_NAME]]));
    await metricsReducerView.assertPanel(METRIC_NAME);

    // we have to click on the "Refresh" button must because the panel is not displayed when landing
    // FIXME fix the plugin code
    await metricsReducerView.appControls.clickOnRefresh();
    await metricsReducerView.assertPanel(METRIC_NAME);

    // we take a screenshot because the badge is displayed via a CSS pseudo element and text assertions do not work
    // we take a screenshot of the whole panel and not only the header because the selector generated by Grafana dev 12 is different from Grafana enterprise 11
    // finally, we don't use the expectScreenshotInCurrentGrafanaVersion fixture here because the panels look alike in Grafana 11 and Grafana 12 (versions supported in July 2025)
    await expect(metricsReducerView.getPanelByTitle(METRIC_NAME)).toHaveScreenshot('native-histogram-panel.png');
  });
});
