FROM docker.io/prom/prometheus:v3.10.0@sha256:4a61322ac1103a0e3aea2a61ef1718422a48fa046441f299d71e660a3bc71ae9

USER nobody

# data from ~ 2025-05-26 11:00 to 2025-05-26 12:05
COPY e2e/provisioning/prometheus/data.zip /prometheus/data.zip
RUN unzip /prometheus/data.zip 
RUN rm /prometheus/data.zip 

COPY e2e/provisioning/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
