FROM docker.io/prom/prometheus:v3.13.2@sha256:508729e0e2d18e11fd742a5a5ca70e557b940a93948c3c95fd0123a6fd538b69

USER nobody

# data from ~ 2025-05-26 11:00 to 2025-05-26 12:05
COPY e2e/provisioning/prometheus/data.zip /prometheus/data.zip
RUN unzip /prometheus/data.zip 
RUN rm /prometheus/data.zip 

COPY e2e/provisioning/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
