FROM mcr.microsoft.com/playwright:v1.57.0@sha256:f1e7e01021efd65dd1a2c56064be399f3e4de00fd021ac561325f2bfbb2b837a

WORKDIR /app

# required by the e2e test code
RUN npm install "@playwright/test@^1.57.0" "dotenv@^16.3.1" "@grafana/plugin-e2e"

ENV TZ=Europe/Madrid

ENTRYPOINT ["npx", "playwright", "test", "-c", "e2e/config/playwright.config.ci.ts"]
