FROM mcr.microsoft.com/playwright:v1.50.0

WORKDIR /app

# required by the e2e test code
RUN yarn add "@playwright/test@^1.50.0" "dotenv@^16.3.1" "@grafana/plugin-e2e"

ENV TZ=Europe/Madrid

ENTRYPOINT ["npx", "playwright", "test", "-c", "e2e/config/playwright.config.ci.ts"]
