global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: grafana
    static_configs:
      - targets:
          - host.docker.internal:3001
  - job_name: 'prometheus-utf8'
    static_configs:
      - targets: ['prometheus-utf8:9112']
