global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'grafana-gmd'
    static_configs:
      - targets: ['grafana-gmd:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-gmd:9090']
