name: Bundle Stats

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Node.js version from package.json
        id: node-version
        run: |
          NODE_VERSION=$(node -p "require('./package.json').engines.node.replace('>=', '')")
          echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT

      - name: Compare bundle stats
        uses: grafana/plugin-actions/bundle-size@main
        with:
          node-version: ${{ steps.node-version.outputs.version }}
