name: Publish Dev
run-name: Deploy main to dev by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - fix/cd-dev

permissions:
  contents: 'write'
  id-token: 'write'
  attestations: 'write'

jobs:
  CD:
    name: Deploy plugin
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@main
    with:
      branch: ${{ github.event_name == 'push' && github.ref_name || github.ref }}
      environment: dev
      attestation: true # this guarantees that the plugin was built from the source code provided in the release
      run-playwright: false
      # Use argo workflows, auto merge to dev in deployment tools
      grafana-cloud-deployment-type: provisioned
      auto-merge-environments: dev
      argo-workflow-slack-channel: '#proj-metricsdrilldown-cd'
