name: Publish Dev
run-name: Deploy ${{ inputs.branch }} to dev by @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  CD:
    name: Deploy plugin
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      # When pushing to "main", publish and deploy to "dev" and "ops" (CD). For PRs, skip publishing and deploying (run CI only)
      environment: ${{ (github.event_name == 'push' && github.ref_name == 'main') && 'dev' || 'none' }}
      attestation: true # this guarantees that the plugin was built from the source code provided in the release
      run-playwright: false
      # Use argo workflows, auto merge to dev,ops in deployment tools
      grafana-cloud-deployment-type: provisioned
      auto-merge-environments: dev
      argo-workflow-slack-channel: '#proj-metricsdrilldown-cd'
