name: Publish to plugin catalog
run-name: Deploy ${{ inputs.branch }} to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to publish from. Can be used to deploy PRs to dev
        default: main
      skip-grafana-dev-image:
        description: 'Bypass grafana-dev image for e2e tests'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - chore/pr-ci-improvements

permissions:
  contents: 'write'
  id-token: 'write'
  attestations: 'write'

jobs:
  CD:
    name: Deploy plugin
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@main
    with:
      # When pushing to "main", publish and deploy to "dev" and "ops" (CD). For PRs, skip publishing and deploying (run CI only)
      #environment: ${{ (github.event_name == 'push' && github.ref_name == 'main') && 'dev,ops' || 'none' }}
      environment: ${{ (github.event_name == 'push' && github.ref_name == 'chore/pr-ci-improvements') && 'dev' || 'none' }}
      attestation: true # this guarantees that the plugin was built from the source code provided in the release
      run-playwright: false
      argo-workflow-slack-channel: '#proj-metricsdrilldown-cd'
