name: Publish to plugin catalog
description: Upload new plugin artifact to GCS & publish to plugin catalog

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - ops
          - prod

permissions:
  contents: 'write'
  id-token: 'write'
  attestations: 'write'

jobs:
  CD:
    name: Deploy plugin
    # Don't run on forks
    if: github.repository == 'grafana/metrics-drilldown'
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@main
    with:
      environment: ${{ inputs.environment || 'prod' }}
      upload-playwright-artifacts: true # IMPORTANT: we must ensure there are no unmasked secrets in the E2E tests
      attestation: true # this guarantees that the plugin was built from the source code provided in the release
