name: main - build, upload, deploy to dev+ops

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  check-ci:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - run: echo "CI passed, proceeding with build and release"

  build-latest-version:
    needs: check-ci
    runs-on: ubuntu-latest
    outputs:
      plugin-id: ${{ steps.build.outputs.plugin-id }}

    steps:
      - uses: actions/checkout@v4
        # Only build and release if the repository is grafana/metrics-drilldown (not a fork)
        if: github.repository == 'grafana/metrics-drilldown'

      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          common_secrets: |
            GRAFANA_ACCESS_POLICY_TOKEN=plugins/sign-plugin-access-policy-token:token

      - name: Call shared build action
        id: build
        uses: ./.github/actions/build
        with:
          policy_token: ${{ steps.get-secrets.outputs.GRAFANA_ACCESS_POLICY_TOKEN }}

  upload-to-gcs:
    runs-on: ubuntu-latest
    needs: build-latest-version

    steps:
      - uses: actions/checkout@v4
        # Only build and release if the repository is grafana/metrics-drilldown (not a fork)
        if: github.repository == 'grafana/metrics-drilldown'

      - name: Download zip
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-latest-version.outputs.plugin-id }}-latest.zip

      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          common_secrets: |
            GCP_UPLOAD_ARTIFACTS_KEY=grafana/integration-artifacts-uploader-service-account:'credentials.json'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_UPLOAD_ARTIFACTS_KEY }}'

      - id: 'upload-to-gcs'
        name: 'Upload assets to main'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: ./${{ needs.build-latest-version.outputs.plugin-id }}-latest.zip
          destination: 'integration-artifacts/${{ needs.build-latest-version.outputs.plugin-id }}/'
          parent: false

  deploy-main-to-dev-and-ops:
    needs: build-latest-version
    uses: ./.github/workflows/deploy-to-env.yml
    # Make deployments available only from main
    if: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
    strategy:
      matrix:
        environment: [dev, ops]
    with:
      version: ${{ github.sha }}
      environment: ${{ matrix.environment }}
